/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RekomendasiRouteImport } from './routes/rekomendasi'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as LowonganRouteImport } from './routes/lowongan'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookmarkRouteImport } from './routes/bookmark'
import { Route as IndexRouteImport } from './routes/index'

const RekomendasiRoute = RekomendasiRouteImport.update({
  id: '/rekomendasi',
  path: '/rekomendasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const LowonganRoute = LowonganRouteImport.update({
  id: '/lowongan',
  path: '/lowongan',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarkRoute = BookmarkRouteImport.update({
  id: '/bookmark',
  path: '/bookmark',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmark': typeof BookmarkRoute
  '/dashboard': typeof DashboardRoute
  '/lowongan': typeof LowonganRoute
  '/pengaturan': typeof PengaturanRoute
  '/profil': typeof ProfilRoute
  '/rekomendasi': typeof RekomendasiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmark': typeof BookmarkRoute
  '/dashboard': typeof DashboardRoute
  '/lowongan': typeof LowonganRoute
  '/pengaturan': typeof PengaturanRoute
  '/profil': typeof ProfilRoute
  '/rekomendasi': typeof RekomendasiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmark': typeof BookmarkRoute
  '/dashboard': typeof DashboardRoute
  '/lowongan': typeof LowonganRoute
  '/pengaturan': typeof PengaturanRoute
  '/profil': typeof ProfilRoute
  '/rekomendasi': typeof RekomendasiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmark'
    | '/dashboard'
    | '/lowongan'
    | '/pengaturan'
    | '/profil'
    | '/rekomendasi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmark'
    | '/dashboard'
    | '/lowongan'
    | '/pengaturan'
    | '/profil'
    | '/rekomendasi'
  id:
    | '__root__'
    | '/'
    | '/bookmark'
    | '/dashboard'
    | '/lowongan'
    | '/pengaturan'
    | '/profil'
    | '/rekomendasi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarkRoute: typeof BookmarkRoute
  DashboardRoute: typeof DashboardRoute
  LowonganRoute: typeof LowonganRoute
  PengaturanRoute: typeof PengaturanRoute
  ProfilRoute: typeof ProfilRoute
  RekomendasiRoute: typeof RekomendasiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rekomendasi': {
      id: '/rekomendasi'
      path: '/rekomendasi'
      fullPath: '/rekomendasi'
      preLoaderRoute: typeof RekomendasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lowongan': {
      id: '/lowongan'
      path: '/lowongan'
      fullPath: '/lowongan'
      preLoaderRoute: typeof LowonganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmark': {
      id: '/bookmark'
      path: '/bookmark'
      fullPath: '/bookmark'
      preLoaderRoute: typeof BookmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarkRoute: BookmarkRoute,
  DashboardRoute: DashboardRoute,
  LowonganRoute: LowonganRoute,
  PengaturanRoute: PengaturanRoute,
  ProfilRoute: ProfilRoute,
  RekomendasiRoute: RekomendasiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
