/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RekomendasiRouteImport } from './routes/rekomendasi'
import { Route as LowonganRouteImport } from './routes/lowongan'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const RekomendasiRoute = RekomendasiRouteImport.update({
  id: '/rekomendasi',
  path: '/rekomendasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LowonganRoute = LowonganRouteImport.update({
  id: '/lowongan',
  path: '/lowongan',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/lowongan': typeof LowonganRoute
  '/rekomendasi': typeof RekomendasiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/lowongan': typeof LowonganRoute
  '/rekomendasi': typeof RekomendasiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/lowongan': typeof LowonganRoute
  '/rekomendasi': typeof RekomendasiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/lowongan' | '/rekomendasi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/lowongan' | '/rekomendasi'
  id: '__root__' | '/' | '/dashboard' | '/lowongan' | '/rekomendasi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LowonganRoute: typeof LowonganRoute
  RekomendasiRoute: typeof RekomendasiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rekomendasi': {
      id: '/rekomendasi'
      path: '/rekomendasi'
      fullPath: '/rekomendasi'
      preLoaderRoute: typeof RekomendasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lowongan': {
      id: '/lowongan'
      path: '/lowongan'
      fullPath: '/lowongan'
      preLoaderRoute: typeof LowonganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LowonganRoute: LowonganRoute,
  RekomendasiRoute: RekomendasiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
